config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#top'
  get '/signup', to: 'users#new'

  # ログイン機能
  get    '/login', to: 'sessions#new'
  post   '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users do
    collection {post :import}
      member do
        get 'edit_basic_info'
        patch 'update_basic_info'
        get 'attendances/edit_one_month'
        patch 'attendances/update_one_month' 
        get 'attendances/edit_overwork_request'
        patch 'attendances/update_overwork_request'
        get 'attendances/edit_superior_announcement'
        patch 'attendances/update_superior_announcement'
        get 'attendances/month_approval'
      end
      collection do
        get 'index_attendance'
      end
      resources :attendances, only: :update
    end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :attendances, dependent: :destroy
  # 「remember_token」という仮想の属性を作成します。
  attr_accessor :remember_token
  before_save { self.email = email.downcase }

  validates :name, presence: true, uniqueness: true, length: { maximum: 50 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 100 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true
  validates :department, length: { in: 2..50 }, allow_blank: true
  validates :basic_time, presence: true
  validates :work_time, presence: true
  validates :designated_work_start_time, presence: true
  validates :designated_work_end_time, presence: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  # 渡された文字列のハッシュ値を返します。
  def User.digest(string)
    cost = 
      if ActiveModel::SecurePassword.min_cost
        BCrypt::Engine::MIN_COST
      else
        BCrypt::Engine.cost
      end
    BCrypt::Password.create(string, cost: cost)
  end

  # ランダムなトークンを返します。
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # 永続セッションのためハッシュ化したトークンをデータベースに記憶します。
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # トークンがダイジェストと一致すればtrueを返します。
  def authenticated?(remember_token)
    # ダイジェストが存在しない場合はfalseを返して終了します。
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # ユーザーのログイン情報を破棄します。
  def forget
    update_attribute(:remember_digest, nil)
  end
  
  def self.search(search) #ここでのself.はUser.を意味する
    if search
      where(['name LIKE ?', "%#{search}%"]) #検索とnameの部分一致を表示。User.は省略
    else
      all #全て表示。User.は省略
    end
  end
  
    #importメソッド
  def self.import(file)
    ApplicationRecord.transaction do
    CSV.foreach(file.path, headers: true) do |row|
      # IDが見つかれば、レコードを呼び出し、見つかれなければ、新しく作成
      user = find_by(id: row["id"]) || new
      # CSVからデータを取得し、設定する
      user.attributes = row.to_hash.slice(*updatable_attributes)
      user.save!
    rescue ActiveRecord::RecordInvalid
      false
    end
   end
  end
  
  # 更新を許可するカラムを定義
  def self.updatable_attributes
    ["name", "user_id", "email", "department", 
     "basic_time", "designated_work_start_time",
     "designated_work_end_time", "password"]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :edit_basic_info, :update_basic_info]
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy, :edit_basic_info, :update_basic_info]
  before_action :correct_user, only: [:edit, :update, :show]
  before_action :admin_user, only: [:destroy, :update, :edit_basic_info, :update_basic_info]
  before_action :set_one_month, only: :show

  def index
    @users = User.all
    # respond_to do |format|
    #   format.html do
    #     #html用の処理を書く
    # end 
    #   format.csv do
    #     #csv用の処理を書く
    #     send_data render_to_string, filename: "(ファイル名).csv", type: :csv
    # end
  end
    
    # if params[:name].present?
    #   @users = User.get_by_name params[:name]
    # end
    # if params[:id].present?
    #   @user = User.find_by(id: @users.id)
    # else
    #   @user = User.new
    # end
  # end
  
  def index_attendance
    @users = User.all.includes(:attendances)
  end
      
  
  def import
    if params[:csv_file].blank?
      redirect_to action: 'index', error: '読み込むCSVを選択してください'
    elsif File.extname(params[:csv_file].original_filename) != ".csv"
      redirect_to action: 'index', notice: 'csvファイルのみ読み込み可能です'
    # elsif User.exists?(name: "濱本 亮")
      # redirect_to action: 'index', notice: 'そのユーザーはすでに存在しています'
    else
       results = User.import(params[:csv_file])
       redirect_to action: 'index', notice: "#{ results.to_s }件のエラーが発生しました"
        p  results.failed_instances  # 戻り値で、失敗したインスタンスを配列で取得する
      # num = User.import(params[:csv_file])
      # redirect_to action: 'index', notice: "#{ num.to_s }件のデータ情報を追加/更新しました"
    end
  end
  
  def show
    @user = User.find(params[:id])
    @worked_sum = @attendances.where.not(started_at: nil).count
    @attendance = Attendance.where(confirmation: '申請中')
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = '新規作成に成功しました。'
      redirect_to @user
    else
      render :new
    end
  end

  def edit
  end

  def update
    @users = User.paginate(page: params[:page], per_page: 20)
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "ユーザー情報を更新しました。"
      redirect_to @user
    else
      render :index   
    end
  end

  def destroy
    @user.destroy
    flash[:success] = "#{@user.name}のデータを削除しました。"
    redirect_to users_url
  end

  def edit_basic_info
    if current_user.admin?
      @user = User.find(params[:id])
    end
  end

  def update_basic_info
    if @user.update_attributes(basic_info_params)
      flash[:success] = "#{@user.name}の基本情報を更新しました。"
    else
      flash[:danger] = "#{@user.name}の更新は失敗しました。<br>" + @user.errors.full_messages.join("<br>")
    end
    redirect_to users_url
  end
  
  
  
  
  private

    def user_params
      params.require(:user).permit(:name, :email, :department, :designated_work_end_time, :designated_work_start_time, :password, :password_confirmation)
    end

    def basic_info_params
      params.require(:user).permit(:department, :basic_time, :work_time)
    end
    
    
    
    def search
    #Viewのformで取得したパラメータをモデルに渡す
    @users = User.search(params[:search])
    end
end

app/helpers/users_helper.rb
module UsersHelper

  # 勤怠基本情報を指定のフォーマットで返します。  
  def format_basic_info(time)
    format("%.2f", ((time.hour * 60) + time.min) / 60.0)
  end
end

app/views/users/_edit_basic_info.html.erb
<% provide(:class_text, 'basic-info') %>
<% provide(:button_text, '更新') %>

<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">×</span>
      </button>
      <h1 class="modal-title">基本情報編集</h1>
    </div>
    <div class="modal-body">
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <%= form_with(model: @user, url: update_basic_info_user_path(@user), local: true, method: :patch) do |f| %>
            <%= render 'shared/error_messages', object: @user %>

            <%= f.label :name, class: "label-#{yield(:class_text)}" %>
            <p><%= @user.name %></p><br>

            <%= f.label :department, class: "label-#{yield(:class_text)}" %>
            <%= f.text_field :department, class: "form-control" %>

            <%= f.label :basic_time, class: "label-#{yield(:class_text)}" %>
            <%= f.time_field :basic_time, class: "form-control" %>

            <%= f.label :work_time, class: "label-#{yield(:class_text)}" %>
            <%= f.time_field :work_time, class: "form-control" %>

            <div class="center">
              <%= f.submit yield(:button_text), class: "btn btn-primary btn-#{yield(:class_text)}" %>
              <button type="button" class="btn btn-default btn-<%= yield(:class_text) %>" data-dismiss="modal">
                キャンセル
              </button>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/_form.html.erb
<%= form_with(model: @user, local: true) do |f| %>
  <%= render 'shared/error_messages', object: @user %>

  <%= f.label :name, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :name, class: "form-control" %>

  <%= f.label :email, class: "label-#{yield(:class_text)}" %>
  <%= f.email_field :email, class: "form-control" %>

  <%= f.label :department, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :department, class: "form-control" %>

  <%= f.label :password, class: "label-#{yield(:class_text)}" %>
  <%= f.password_field :password, class: "form-control" %>

  <%= f.label :password_confirmation, class: "label-#{yield(:class_text)}" %>
  <%= f.password_field :password_confirmation, class: "form-control" %>

  <%= f.submit yield(:button_text), class: "btn btn-primary btn-block btn-#{yield(:class_text)}" %>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, "Edit") %>
<% provide(:class_text, 'user--edit') %>
<% provide(:button_text, '更新') %>
<h1>ユーザー情報の更新</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/edit_basic_info.js.erb
$("#edit-basic-info").html("<%= escape_javascript(render 'edit_basic_info') %>");
$("#edit-basic-info").modal("show");

app/views/users/form1.html.erb
<%= form_with(model:@user,local: true) do |f| %>


  <%= f.label :name, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :name, class: "form-control" %>
  
  <%= f.label :email, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :email, class: "form-control" %>
  
  <%= f.label :department, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :department, class: "form-control" %>
  
  <%= f.label :employee_number, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :employee_number, class: "form-control" %>
  
  <%= f.label :user_id, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :user_id, class: "form-control" %>
  
  <%= f.label :password, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :password, class: "form-control" %>
  
  <%= f.label :basic_time, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :basic_time, class: "form-control" %>
  
  <%= f.label :designated_work_start_time, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :designated_work_start_time, class: "form-control" %>
  
  <%= f.label :designated_work_end_time, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :designated_work_end_time, class: "form-control" %>
  
  <%= f.submit "編集する", class: "btn btn-primary btn-block btn-#{yield(:class_text)}" %>
<% end %>

app/views/users/index.html.erb
<% provide(:title, 'All Users') %>
<h1>ユーザー一覧</h1>
  
<%= form_tag import_users_path, method: :post, multipart: true do %>
  <%= file_field_tag :csv_file %>
  <%= submit_tag "CSVをインポート" , class: "btn btn-primary" %> <!--“csvインポート“はbuttonタグで代用可能です。-->
<% end %>


  <table class="table">
    <% @users.each do |user| %>
      <tr>
        <td>
          <div class="col-md-22 col-md-offset-1">
          <% if current_user.admin? && !current_user?(user) %>
          <%= user.name %><br>
          |  <%= link_to "削除", user, method: :delete,
                            data: { confirm: "削除してもよろしいですか？" },
                            class: "btn btn-primary btn-default" %><br>
            <div class="panel-group">
              <div class="panel panel-default">
                <h4 class="panel-title">
                  <button type="button" data-toggle="collapse" data-target="#collapse<%= user.id %>" class="btn btn-primary btn-default">編集</button>
                </h4>
              </div>
              <div id="collapse<%= user.id %>" class="panel-collapse collapse">
                <div class="panel-body">
                  <%= form_with(model:@user,local: true) do |f| %>


                    <%= f.label :name, class: "label-#{yield(:class_text)}" %>
                    <%= f.text_field :name, class: "form-control" %>
                    
                    <%= f.label :email, class: "label-#{yield(:class_text)}" %>
                    <%= f.email_field :email, class: "form-control" %>
                    
                    <%= f.label :department, class: "label-#{yield(:class_text)}" %>
                    <%= f.text_field :department, class: "form-control" %>
                    
                    <%= f.label :password, class: "label-#{yield(:class_text)}" %>
                    <%= f.password_field :password, class: "form-control" %>
                    
                    <%= f.label :basic_time, class: "label-#{yield(:class_text)}" %>
                    <%= f.time_field :basic_time, class: "form-control" %>
                    
                    <%= f.label :designated_work_start_time, "指定勤務開始時間", class: "label-#{yield(:class_text)}" %>
                    <%= f.time_field :designated_work_start_time, class: "form-control" %>
                    
                    <%= f.label :designated_work_end_time, "指定勤務終了時間", class: "label-#{yield(:class_text)}" %>
                    <%= f.time_field :designated_work_end_time, class: "form-control" %>
                    
                    <%= f.submit "編集する", class: "btn btn-primary btn-block btn-#{yield(:class_text)}" %>
                  <% end %>
                </div>
              </div>
            </div>
          <% end %>  
          </div>
        </td>
      </tr>
    <% end %>
  </table>
  <!--モーダルウィンドウ表示-->
  <div id="edit_basic_info" class="modal fade" tabindex="1" role="dialog" aria-hidden="true"></div>

app/views/users/index_attendance.html.erb
<% provide(:title, "出勤中社員一覧") %>
<h1>出勤中社員一覧</h1>

<div>
  <table class="table table-bordered table-condensed table-hover text-center table-striped" id="index_attendance">
    <thead>
      <tr>
        <th>社員番号</th>
        <th>名前</th>
      </tr>  
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <% user.attendances.each do |attendance| %>
          <% if (Date.current == attendance.worked_on) && attendance.finished_at.nil? %>
          <tr>
            <td><%= user.id %></td>
            <td><%= user.name %></td>
          </tr>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<% provide(:class_text, 'signup') %>
<% provide(:button_text, '新規作成') %>
<h1>ユーザー登録</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/show.html.erb
<% unless current_user.admin? %>
<% provide(:title, @user.name) %>
<div>
  <table class="table table-bordered table-condensed user-table">
    <tr>
      <td><%= link_to "⇦ ", user_path(date: @first_day.prev_month), class: "btn btn-default" %> 【<%= l(@first_day, format: :middle) %>】勤怠管理表<%= link_to "⇨", user_path(date: @first_day.next_month), class: "btn btn-default" %></td>
      <!-- app/helpers/users_helper.rbに定義済み-->
      <td>指定勤務時間：<%= format_basic_info(@user.work_time) %></td>
      <!-- app/helpers/users_helper.rbに定義済み-->
      <td>基本時間：<%= format_basic_info(@user.basic_time) %></td>
      <td>指定勤務開始時間<%= l(@user.designated_work_start_time, format: :time) %></td>
      <td>初日 : <%= l(@first_day, format: :short) %></td>
    </tr>

    <tr>
      <td>所属：<%= @user.department.present? ? @user.department : "未所属" %></td>
      <td>氏名：<%= @user.name %></td>
      <td>出勤日数 : <%= @worked_sum %>日</td>
      <td>指定勤務終了時間: <%= l(@user.designated_work_end_time, format: :time) %></td>
      <td>月末日 : <%= l(@last_day, format: :short) %></td> <!-- config/locales/ja.ymlの40行目あたり-->
    </tr>
  </table>
</div>

<% if current_user.superior? %>
  <div>
    <p class="">【 所属長承認申請のお知らせ 】</p><br>
    <p class="">【 勤怠変更申請のお知らせ 】</p><br>
    <%= link_to"【 残業申請のお知らせ 】", attendances_edit_superior_announcement_user_path(@user), remote: true %>
      <% if @attendances.present? || confirmation == "申請中" %>
        <%= @attendance.count%>件の通知があります。<br>
      <% end %>
    <p class=""></p><br>
  </div>
<% end %>

<div class="btn-users-show">
  <%= link_to "勤怠を編集", attendances_edit_one_month_user_path(date: @first_day), class: "btn btn-default active" %>
  <%= link_to "CSV出力", class: "btn btn-default active" %>
  <%= link_to "勤怠修正ログ(承認済）", class: "btn btn-default active" %>
</div>

<div>
  <table class="table table-bordered table-condensed table-hover" id="table-attendances">
    <thead>
      <tr>
        <th></th>
        <th colspan="9">実績</th>
        <th colspan="4">所定外勤務</th>
      </tr>
      <tr>
        <th></th>
        <th></th>
        <th colspan="3">出社</th>
        <th colspan="2">退社</th>
        <th></th>
        <th></th>
        <th></th>
        <th rowspan="2">終了予定時間</th>
        <th rowspan="2">時間外時間</th>
        <th rowspan="2">業務処理内容</th>
        <th rowspan="2">支持者確認㊞</th>
      </tr>
      <tr>
        <th></th>
        <th>日付</th>
        <th>曜日</th>
        <th>時</th>
        <th>分</th>
        <th></th>
        <th>時</th>
        <th>分</th>
        <th>在社時間</th>
        <th>備考</th>
      </tr>
    </thead>

    <tbody>
      <% @attendances.each do |day| %>
        <tr>
          <td><%= link_to "残業申請", attendances_edit_overwork_request_user_path(@user, day: day.worked_on), remote: true, class: "btn btn-primary" %></td>
          <td><%= l(day.worked_on, format: :short) %></td>
          <td>
            <% if day.worked_on.wday == 0 %>
              <font color="RED"><%= $days_of_the_week[day.worked_on.wday] %></font>
            <% elsif day.worked_on.wday == 6 %>
              <font color="Blue"><%= $days_of_the_week[day.worked_on.wday] %></font>
            <% else %>
              <%= $days_of_the_week[day.worked_on.wday] %>
            <% end %>
          </td>
          <td><%= day.started_at.hour if day.started_at.present? %></td>
          <td><%= format_min(day.started_at) if day.started_at.present? %></td>
          <td>
            <% if btn_text = attendance_state(day) %>
              <%= link_to "#{btn_text}", user_attendance_path(@user, day), method: :patch, class: "btn btn-default active" %>
            <% end %>
          </td>
          <td><%= day.finished_at.hour if day.finished_at.present? %></td>
          <td><%= format_min(day.finished_at) if day.finished_at.present? %></td>
          <td>
            <% if day.started_at.present? && day.finished_at.present? %>
              <%= str_times = working_times(day.started_at, day.finished_at) %>
              <% @total_working_times = @total_working_times.to_f + str_times.to_f %>
            <% end %>
          </td>
          <td><%= day.note %></td>
          <td>
            <% unless day.scheduled_end_time.nil? %>
              <%= l(day.scheduled_end_time, format: :time) %>
            <% end %>
          </td>
          <td>
            <% if day.scheduled_end_time.present? && @user.designated_work_end_time.present? %>
              <%= overtime_status(day.scheduled_end_time, @user.designated_work_end_time) %>
            <% end %>
          </td>
          <td><%= day.business_process %></td>
          <td><%= day.confirmation %></td>
        </tr>  
      <% end %>
    </tbody>
    
    <tfoot>
      <!--rowspan:縦結合、colspan：横結合-->
      <tr>
        <td colspan="2">累計日数</td>
        <td colspan="2">総合勤務時間</td>
        <td colspan="2">累計在社時間</td>
        <td rowspan="2"></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td>所属長確認</td>
      </tr>
      <tr>
        <td colspan="2"><%= @attendances.count %></td>
        <td colspan="2"><%= format_basic_info(@user.work_time).to_f * @worked_sum %></td>
        <td colspan="2"><%= format("%.2f", @total_working_times.to_f) %></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td><select class="form-control">
          <option></option>
        </select></td>
      </tr>
      <tr>
        <td colspan="2"></td>
        <td colspan="2"></td>
        <td colspan="2"></td>
        <td rowspan="2"></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td><%= link_to "申請", remote: true, class: "btn btn-primary" %></td>
      </tr>
    </tfoot>    
  </table>
</div>

<!--モーダルウインドウ表示-->
<div id="edit-overwork-request" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
<div id="edit-superior-announcement" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
<% end %>


<% if current_user.admin? %>
<div>
  <table class="table table-bordered table-condensed user-table">
    <tr>
      <td><%= link_to "⇦ ", user_path(date: @first_day.prev_month), class: "btn btn-default" %> 【<%= l(@first_day, format: :middle) %>】勤怠管理表<%= link_to "⇨", user_path(date: @first_day.next_month), class: "btn btn-default" %></td>
      <!-- app/helpers/users_helper.rbに定義済み-->
      <td>指定勤務時間：<%= format_basic_info(@user.work_time) %></td>
      <!-- app/helpers/users_helper.rbに定義済み-->
      <td>基本時間：<%= format_basic_info(@user.basic_time) %></td>
      <td>指定勤務開始時間<%= l(@user.designated_work_start_time, format: :time) %></td>
      <td>初日 : <%= l(@first_day, format: :short) %></td>
    </tr>

    <tr>
      <td>所属：<%= @user.department.present? ? @user.department : "未所属" %></td>
      <td>氏名：<%= @user.name %></td>
      <td>出勤日数 : <%= @worked_sum %>日</td>
      <td>指定勤務終了時間: <%= l(@user.designated_work_end_time, format: :time) %></td>
      <td>月末日 : <%= l(@last_day, format: :short) %></td> <!-- config/locales/ja.ymlの40行目あたり-->
    </tr>
  </table>
</div>

<div>
  <table class="table table-bordered table-condensed table-hover" id="table-attendances">
    <thead>
      <tr>
        <th></th>
        <th colspan="9">実績</th>
        <th colspan="4">所定外勤務</th>
      </tr>
      <tr>
        <th></th>
        <th></th>
        <th colspan="3">出社</th>
        <th colspan="2">退社</th>
        <th></th>
        <th></th>
        <th></th>
        <th rowspan="2">終了予定時間</th>
        <th rowspan="2">時間外時間</th>
        <th rowspan="2">業務処理内容</th>
        <th rowspan="2">支持者確認㊞</th>
      </tr>
      <tr>
        <th></th>
        <th>日付</th>
        <th>曜日</th>
        <th>時</th>
        <th>分</th>
        <th></th>
        <th>時</th>
        <th>分</th>
        <th>在社時間</th>
        <th>備考</th>
      </tr>
    </thead>

    <tbody>
      <% @attendances.each do |day| %>
        <tr>
          <td><%= link_to "残業申請", attendances_edit_overwork_request_user_path(@user, day: day.worked_on), remote: true, class: "btn btn-primary" %></td>
          <td><%= l(day.worked_on, format: :short) %></td>
          <td>
            <% if day.worked_on.wday == 0 %>
              <font color="RED"><%= $days_of_the_week[day.worked_on.wday] %></font>
            <% elsif day.worked_on.wday == 6 %>
              <font color="Blue"><%= $days_of_the_week[day.worked_on.wday] %></font>
            <% else %>
              <%= $days_of_the_week[day.worked_on.wday] %>
            <% end %>
          </td>
          <td><%= day.started_at.hour if day.started_at.present? %></td>
          <td><%= format_min(day.started_at) if day.started_at.present? %></td>
          <td>
            <% if btn_text = attendance_state(day) %>
              <%= link_to "#{btn_text}", user_attendance_path(@user, day), method: :patch, class: "btn btn-default active" %>
            <% end %>
          </td>
          <td><%= day.finished_at.hour if day.finished_at.present? %></td>
          <td><%= format_min(day.finished_at) if day.finished_at.present? %></td>
          <td>
            <% if day.started_at.present? && day.finished_at.present? %>
              <%= str_times = working_times(day.started_at, day.finished_at) %>
              <% @total_working_times = @total_working_times.to_f + str_times.to_f %>
            <% end %>
          </td>
          <td><%= day.note %></td>
          <td>
            <% unless day.scheduled_end_time.nil? %>
              <%= l(day.scheduled_end_time, format: :time) %>
            <% end %>
          </td>
          <td>
            <% if day.scheduled_end_time.present? && @user.designated_work_end_time.present? %>
              <%= overtime_status(day.scheduled_end_time, @user.designated_work_end_time) %>
            <% end %>
          </td>
          <td><%= day.business_process %></td>
          <td><%= day.confirmation %></td>
        </tr>  
      <% end %>
    </tbody>
    
    <tfoot>
      <!--rowspan:縦結合、colspan：横結合-->
      <tr>
        <td colspan="2">累計日数</td>
        <td colspan="2">総合勤務時間</td>
        <td colspan="2">累計在社時間</td>
        <td rowspan="2"></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td>所属長確認</td>
      </tr>
      <tr>
        <td colspan="2"><%= @attendances.count %></td>
        <td colspan="2"><%= format_basic_info(@user.work_time).to_f * @worked_sum %></td>
        <td colspan="2"><%= format("%.2f", @total_working_times.to_f) %></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td><select class="form-control">
          <option></option>
        </select></td>
      </tr>
      <tr>
        <td colspan="2"></td>
        <td colspan="2"></td>
        <td colspan="2"></td>
        <td rowspan="2"></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td><%= link_to "申請", remote: true, class: "btn btn-primary" %></td>
      </tr>
    </tfoot>    
  </table>
</div>

<!--モーダルウインドウ表示-->
<div id="edit-overwork-request" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
<div id="edit-superior-announcement" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
<% end %>