config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#top'
  get '/signup', to: 'users#new'

  # ログイン機能
  get    '/login', to: 'sessions#new'
  post   '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users do
    collection {post :import}
      member do
        get 'edit_basic_info'
        patch 'update_basic_info'
        get 'attendances/edit_one_month'
        patch 'attendances/update_one_month' 
        get 'attendances/edit_overwork_request'
        patch 'attendances/update_overwork_request'
        get 'attendances/edit_superior_announcement'
        patch 'attendances/update_superior_announcement'
        get 'attendances/month_approval'
      end
      collection do
        get 'index_attendance'
      end
      resources :attendances, only: :update
    end
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :user

  validates :worked_on, presence: true
  validates :note, length: { maximum: 50 }

  # 出勤時間が存在しない場合、退勤時間は無効
  validate :finished_at_is_invalid_without_a_started_at
  # 出勤・退勤時間どちらも存在する時、出勤時間より早い退勤時間は無効
  validate :started_at_than_finished_at_fast_if_invalid
  
  validate :started_at_is_invalid_without_a_finished_at, on: :attendance_update
  
  
  def finished_at_is_invalid_without_a_started_at
    errors.add(:started_at, "が必要です") if started_at.blank? && finished_at.present?
  end

  def started_at_than_finished_at_fast_if_invalid
    if started_at.present? && finished_at.present?
      errors.add(:started_at, "より早い退勤時間は無効です") if started_at > finished_at
    end
  end
  
  def started_at_is_invalid_without_a_finished_at
    errors.add(:finished_at, "が必要です") if started_at.present? && finished_at.blank?
  end
  
  DeliveryType = {
    "申請中" => "applying",
    "承認" => "approval",
    "否認" => "cancel",
  }
  
  DeliveryTypePattern = {
    "approval" => {status: :success, message: "承認完了しました。"},
    "applying" => {status: :danger, message: "指示者確認が申請中のままです。"},
    "unknown" => {status: :danger, message: "不正なステータスが送信されました。"},
    "cancel" => {status: :danger, message: "残業申請が否認されました。"}
  }
  
  def export_confirm_result(status)
    if status == DeliveryType["approval"]
      DeliveryTypePattern["approval"]
    elsif status == DeliveryType["applying"]
      DeliveryTypePattern["applying"]
    elsif status == DeliveryType["cancel"]
      DeliveryTypePattern["cancel"]
    else
      DeliveryTypePattern["unknown"]
    end
  end
  
  def self.confirm_approval?(string)
    string == DeliveryType.find {|k,v| v == "approval" }
  end
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  before_action :set_user, only: [:edit_one_month, :update_one_month, :month_approval]
  before_action :logged_in_user, only: [:update, :edit_one_month]
  before_action :admin_or_correct_user, only: [:update, :edit_one_month, :update_one_month]
  before_action :set_one_month, only: [:edit_one_month, :month_approval]

  UPDATE_ERROR_MSG = "勤怠登録に失敗しました。やり直してください。"

  def update
    @user = User.find(params[:user_id])
    @attendance = Attendance.find(params[:id])
    # 出勤時間が未登録であることを判定します。
    if @attendance.started_at.nil?
      if @attendance.update_attributes(started_at: Time.current.change(sec: 0))
        flash[:info] = "おはようございます！"
      else
        flash[:danger] = UPDATE_ERROR_MSG
      end
    elsif @attendance.finished_at.nil?
      if @attendance.update_attributes(finished_at: Time.current.change(sec: 0))
        flash[:info] = "お疲れ様でした。"
      else
        flash[:danger] = UPDATE_ERROR_MSG
      end
    end
    redirect_to @user
  end

  def edit_one_month
  end

  def update_one_month
    ActiveRecord::Base.transaction do # トランザクションを開始します。
      attendances_params.each do |id, item|
        attendance = Attendance.find(id)
        attendance.update_attributes!(item)
        attendance.attributes = item
        attendance.save!(context: :attendance_update)
      end
    end
    flash[:success] = "1ヶ月分の勤怠情報を更新しました。"
    redirect_to user_url(date: params[:date])
  rescue ActiveRecord::RecordInvalid # トランザクションによるエラーの分岐です。
    flash[:danger] = "無効な入力データがあった為、更新をキャンセルしました。"
    redirect_to attendances_edit_one_month_user_url(date: params[:date])
  end
  
  def edit_overwork_request
    @day = Date.parse(params[:day])
    @user = User.find(params[:id])
    @attendance = @user.attendances.find_by(worked_on: @day)
  end
  
  def update_overwork_request
    @day = Date.parse(params[:day])
    @user = User.find(params[:id])
    @attendance = @user.attendances.find_by(worked_on: @day)
    @attendance.update_attributes(overwork_params)
    flash[:success] = "残業を申請しました。"
    redirect_to @user
    
   if params[:attendance][:scheduled_end_time].blank? && params[:attendance][:business_process].blank?
     flash[:danger] = "終了予定時間及び業務処理内容が空です。"
     redirect_to user_url(@user) and return
   end
   
   if params[:attendance][:scheduled_end_time].blank?
     flash[:danger] = "終了予定時間が空です。"
     redirect_to user_url(@user) and return
   end
   
   if params[:attendance][:business_process].blank?
     flash[:danger] = "業務処理内容が空です。"
     redirect_to user_url(@user) and return
   end
   
  end
  
  # 残業申請承認モーダル
  def edit_superior_announcement
    @user = User.find(params[:id])
    @attendance = Attendance.find(params[:id])
    @attendances = Attendance.where(confirmation: '申請中', instructor_confirmation: @user.id).order(:user_id).group_by(&:user_id)
  end
  
  
  def update_superior_announcement
    @user = User.find(params[:id])
    attendance_ids = params[:attendance][:attendances].keys # ["59", "89", "119"]
    attendance_ids.each do |id|
      if params[:attendance][:attendances][id]["confirmation"] == "承認"
        Attendance.find(id).update!(confirmation: "承認")
        flash[:success] = "残業申請承認完了しました。"
        redirect_to user_url(@user) and return
      else
        flash[:danger] = "不正なステータスが送信されました。"
        redirect_to user_url(@user) and return
      end
    end
  #  @user = User.find(params[:id])
    # @status_messages = [:danger, :message, "不正なステータスが送信されました。",
    #                     :success, :message, "残業申請承認完了しました。"]
    # status_message = {}
    # ActiveRecord::Base.transaction do
    #   begin
    #     @attendances = Attendance.where(confirmation: "申請中")
    #                             .where(instructor_confirmation: params[:id])
    #                             .where(id: params[:attendance][:attendances].keys)
                                 
    #     @attendances.each do |attendance|
          
    #       status_message = attendance.export_confirm_result(params[:attendance][:attendances][attendance.id.to_s][:confirmation])
    #       if Attendance.confirm_approval?(params[:attendance][:attendances][attendance.id.to_s][:confirmation])
    #       @attendance.save!(overwork_params)
    #       flash[status_message[:success]] << status_message[:message]
    #       end
    #     end
    #   rescue => e
    #     flash[status_message[:danger]] << status_message[:message]
    #     puts e
    #   end
  end
    
    
   # if @attendance.confirmation = "申請中"
    #  flash[:danger] = "指示者確認が申請中のままです。"
     # redirect_to user_url(@user) and return
    #end
    
    #if @attendance.confirmation = "承認"
     # @attendance.save!
      #flash[:success] = "#{@attendance.instructor_confirmation}による残業承認完了しました。"
      #redirect_to user_url(@user) and return
  #  end
    
  #  if @attendance.update_attributes(overwork_params)
      # 更新成功時の処理
   #   flash[:success] = "#{@user.name}の残業申請は承認されました。"
    #  redirect_to user_url(@user)
    #else
      # 更新失敗時の処理
     # flash[:danger] = "#{@user.name}の申請が失敗しました。" + @user.errors.full_messages.join(" 、")
      #redirect_to user_url(@user)
    #end
  
  # 勤怠申請モーダルの確認ボタン
  def month_approval
    @user = User.find(params[:id])
    @attendance = Attendance.find(params[:id])
    @first_day = @attendance.worked_on.beginning_of_month
    @last_day = @first_day.end_of_month
    @attendances = @user.attendances.where(worked_on: @first_day..@last_day).order(:worked_on) #order日付順に並び替える、..は～から～まで
    @worked_sum = @attendances.where.not(started_at: nil).count
  end
  
  
  private

    def attendances_params
      params.require(:user).permit(attendances: [:started_at, :finished_at, :note])[:attendances]
    end
    
    def overwork_params
      params.require(:attendance).permit(:scheduled_end_time, :next_day, :overtime_status, :business_process, :confirmation, :change, :instructor_confirmation)
    end
  
    
    def admin_or_correct_user
      @user = User.find(params[:user_id]) if @user.blank?
      unless current_user?(@user) || current_user.admin?
        flash[:danger] = "編集権限がありません。"
        redirect_to(root_url)
      end  
    end
  
end

app/helpers/attendances_helper.rb
module AttendancesHelper

  def attendance_state(attendance)
    # 受け取ったAttendanceオブジェクトが当日と一致するか評価します。
    if Date.current == attendance.worked_on
      return '出社' if attendance.started_at.nil?
      return '退社' if attendance.started_at.present? && attendance.finished_at.nil?
    end
    # どれにも当てはまらなかった場合はfalseを返します。
    return false
  end

  # 出勤時間と退勤時間を受け取り、在社時間を計算して返します。
  def working_times(start, finish)
    format("%.2f", (((finish - start) / 60) / 60.0))
  end
  
  # 時間外時間の計算
  def overtime_status(scheduled_end_time, designated_work_end_time)
    format("%.2f", (((scheduled_end_time - designated_work_end_time) / 60) / 60.0))
  end
  
  def format_min(time)
    format("%.2d",((time.strftime('%M').to_i / 15).round) * 15)
  end
end

app/views/attendances/_edit_overwork_request.html.erb
<%= form_with(model: @attendance, url:attendances_update_overwork_request_user_path(@user,day:@day), local: true, method: :patch) do |f| %>
  <div class="modal-dialog modal-lg modal-dialog-center">
   <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <h1 class="modal-title">残業申請</h1>
    </div>
    <div class="modal-body">
      <div class="row">
        <div class="col-md-10 col-md-offset-1">
          <table class="table table-bordered table-condensed table-striped user-table">
            <thead>
              <th>日付</th>
              <th>曜日</th>
              <th>終了予定時間</th>
              <th>翌日</th>
              <th>業務処理内容</th>
              <th>指示者確認㊞</th>
              <th>申請先</th>
            </thead>
            
            <tbody>
                  <td><%= l(@day, format: :short) %></td>
                  <% if @day.wday == 6 %>
                    <td class="sat"><%= $days_of_the_week[@day.wday] %>
                  <% elsif @day.wday == 0 %>
                    <td class="sun"><%= $days_of_the_week[@day.wday] %>
                  <% else %>
                    <td><%= $days_of_the_week[@day.wday] %></td>
                  <% end %>
                  <td><%= f.time_field :scheduled_end_time, class: "form-control" %></td>
                  <td><%= f.check_box :next_day, id: "next_day" %></td>
                  <td><%= f.text_field :business_process, class: "form-control" %></td>
                  <td><%= f.select :confirmation, [["なし", "なし"], ["申請中", "申請中"], ["承認", "承認"], ["否認", "否認"]], class: "form-control" %></td>
                  <td><%= f.select :instructor_confirmation, [["上長", 2]], class: "form-control" %></td>
            </tbody>
          </table>
          
          <div class="center">
            <%= f.submit "送信する", class: "btn btn-primary btn-block btn-user" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/attendances/_edit_superior_announcement.html.erb
<%= form_with(model: @attendance, url:attendances_update_superior_announcement_user_path(@user), local: true, method: :patch) do |f| %>
  <div class="modal-dialog modal-lg modal-dialog-center">
    <div class="modal-content">
      <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <% @attendances.each do |id, items| %>
        <% user = User.find(id) %>
        <h1 class="modal-title"> 【 <%= user.name %>からの残業申請】</h1>
        <div class="modal-body">
          <table class="table table-bordered table-condensed table-hover" id="table-overwork-day">
            <thead>
              <tr>
                <th>日付</th>
                <th>曜日</th>
                <th>終了予定時間</th>
                <th>指定勤務終了時間</th>
                <th>時間外時間</th>
                <th>業務処理内容</th>
                <th>指示者確認㊞</th>
                <th>変更</th>
                <th>勤怠を確認する</th>
              </tr>
            </thead>
            <tbody>
              <% items.each do |item| %>
                <%= f.fields_for "attendances[]", item do |attendance| %>
            <tr>
                  <td><%= l(item.worked_on, format: :short) %></td>
                  <td>
                    <% if item.worked_on.wday == 0 %>
                      <font color="RED"><%= $days_of_the_week[item.worked_on.wday] %></font>
                    <% elsif item.worked_on.wday == 6 %>
                      <font color="Blue"><%= $days_of_the_week[item.worked_on.wday] %></font>
                    <% else %>
                      <%= $days_of_the_week[item.worked_on.wday] %>
                    <% end %>  
                  </td>
                  <td>
                    <% unless item.scheduled_end_time.nil? %>
                      <%= l(item.scheduled_end_time, format: :time) %>
                    <% end %>
                  </td>
                  <td><%= l(user.designated_work_end_time, format: :time) %></td>
                  <td>
                    <% if item.scheduled_end_time.present? && user.designated_work_end_time.present? %>
                      <%= overtime_status(item.scheduled_end_time, user.designated_work_end_time) %>
                    <% end %>
                  </td>
                  <td><%= item.business_process %></td>
                  <td><%= attendance.select :confirmation, [["なし", "なし"], ["申請中", "申請中"], ["承認", "承認"], ["否認", "否認"]], class: "form-control" %></td>
                  <td><%= attendance.check_box :change, id: "change" %></td>
                  <td><%= link_to "勤怠を確認", attendances_month_approval_user_path(user), class: "btn btn-default active" %></td>
                <% end %>
              <% end %>
            </tr>
            </tbody>
          </table>
        </div>
      <% end %>
      <div class="button_wrapper">
        <%= f.submit "変更を送信する", remote: true, class: "btn btn-primary btn-block btn-user" %>
      </div>
      </div>
    </div>
  </div>
<% end %>

app/views/attendances/edit_one_month.html.erb
<% provide(:title, @user.name) %>
<%= form_with(model: @user, url: attendances_update_one_month_user_path(date: @first_day), local: true, method: :patch) do |f| %>
  <div>
    <h1>勤怠編集画面</h1>
    <table class="table table-bordered table-condensed table-hover" id="table-attendances">
      <thead>
        <tr>
          <th>日付</th>
          <th>曜日</th>
          <th>出勤時間</th>
          <th>退勤時間</th>
          <th>在社時間</th>
          <th>備考</th>
        </tr>
      </thead>
      <tbody>
        <% @attendances.each do |day| %>
          <%= f.fields_for "attendances[]", day do |attendance| %>
            <tr>
              <td><%= l(day.worked_on, format: :short) %></td>
              <td><%= $days_of_the_week[day.worked_on.wday] %></td>
              <% if !current_user.admin? && (Date.current < day.worked_on) %>
                <td><%= attendance.time_field :started_at, readonly: true, class: "form-control" %></td>
                <td><%= attendance.time_field :finished_at, readonly: true, class: "form-control" %></td>
              <% else %>
                <td><%= attendance.time_field :started_at, class: "form-control" %></td>
                <td><%= attendance.time_field :finished_at, class: "form-control" %></td>
              <% end %>
              <td>
                <% if day.started_at.present? && day.finished_at.present? %>
                  <%= working_times(day.started_at, day.finished_at) %>
                <% end %>
              </td>
              <td><%= attendance.text_field :note, class: "form-control" %></td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>

  <div class="center">
     <%= link_to "キャンセル", user_path(date: @first_day), class: "btn btn-lg btn-default active" %>
    <%= f.submit "編集を保存する", class: "btn btn-lg btn-default active" %>
  </div>
<% end %>

app/views/attendances/edit_overwork_request.js.erb
$("#edit-overwork-request").html("<%= escape_javascript(render 'edit_overwork_request') %>");
$("#edit-overwork-request").modal("show");

app/views/attendances/edit_superior_announcement.js.erb
$("#edit-superior-announcement").html("<%= escape_javascript(render 'edit_superior_announcement') %>");
$("#edit-superior-announcement").modal("show");

app/views/attendances/month_approval.html.erb
<% provide(:title, @user.name) %>
<div>
  <table class="table table-bordered table-condensed user-table">
    <tr>
      <td><%= link_to "⇦ ", user_path(date: @first_day.prev_month), class: "btn btn-default" %> 【<%= l(@first_day, format: :middle) %>】勤怠管理表<%= link_to "⇨", user_path(date: @first_day.next_month), class: "btn btn-default" %></td>
      <!-- app/helpers/users_helper.rbに定義済み-->
      <td>指定勤務時間：<%= format_basic_info(@user.work_time) %></td>
      <!-- app/helpers/users_helper.rbに定義済み-->
      <td>基本時間：<%= format_basic_info(@user.basic_time) %></td>
      <td>初日 : <%= l(@first_day, format: :short) %></td>
    </tr>

    <tr>
      <td>所属：<%= @user.department.present? ? @user.department : "未所属" %></td>
      <td>氏名：<%= @user.name %></td>
      <td>出勤日数 : <%= @worked_sum %>日</td>
      <td>月末日 : <%= l(@last_day, format: :short) %></td> <!-- config/locales/ja.ymlの40行目あたり-->
    </tr>
  </table>
</div>

<div>
  <table class="table table-bordered table-condensed table-hover" id="table-attendances">
    <thead>
      <tr>
        <th></th>
        <th colspan="9">実績</th>
        <th colspan="3">所定外勤務</th>
      </tr>
      <tr>
        <th></th>
        <th></th>
        <th colspan="3">出社</th>
        <th colspan="2">退社</th>
        <th></th>
        <th></th>
        <th></th>
        <th rowspan="2">時間外時間</th>
        <th rowspan="2">業務処理内容</th>
        <th rowspan="2">支持者確認㊞</th>
      </tr>
      <tr>
        <th></th>
        <th>日付</th>
        <th>曜日</th>
        <th>時</th>
        <th>分</th>
        <th></th>
        <th>時</th>
        <th>分</th>
        <th>在社時間</th>
        <th>備考</th>
      </tr>
    </thead>

    <tbody>
      <% @attendances.each do |day| %>
        <tr>
          <td></td>
          <td><%= l(day.worked_on, format: :short) %></td>
          <td>
            <% if day.worked_on.wday == 0 %>
              <font color="RED"><%= $days_of_the_week[day.worked_on.wday] %></font>
            <% elsif day.worked_on.wday == 6 %>
              <font color="Blue"><%= $days_of_the_week[day.worked_on.wday] %></font>
            <% else %>
              <%= $days_of_the_week[day.worked_on.wday] %>
            <% end %>
          </td>
          <td><%= day.started_at.hour if day.started_at.present? %></td>
          <td><%= format_min(day.started_at) if day.started_at.present? %></td>
          <td></td>
          <td><%= day.finished_at.hour if day.finished_at.present? %></td>
          <td><%= format_min(day.finished_at) if day.finished_at.present? %></td>
          <td>
            <% if day.started_at.present? && day.finished_at.present? %>
              <%= str_times = working_times(day.started_at, day.finished_at) %>
              <% @total_working_times = @total_working_times.to_f + str_times.to_f %>
            <% end %>
          </td>
          <td><%= day.note %></td>
          <td></td>
          <td></td>
          <td></td>
        </tr>  
      <% end %>
    </tbody>
    
    <tfoot>
      <!--rowspan:縦結合、colspan：横結合-->
      <tr>
        <td colspan="2">累計日数</td>
        <td colspan="2">総合勤務時間</td>
        <td colspan="2">累計在社時間</td>
        <td rowspan="2"></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td>所属長確認</td>
      </tr>
      <tr>
        <td colspan="2"><%= @attendances.count %></td>
        <td colspan="2"><%= format_basic_info(@user.work_time).to_f * @worked_sum %></td>
        <td colspan="2"><%= format("%.2f", @total_working_times.to_f) %></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td><select class="form-control">
          <option></option>
        </select></td>
      </tr>
      <tr>
        <td colspan="2"></td>
        <td colspan="2"></td>
        <td colspan="2"></td>
        <td rowspan="2"></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
    </tfoot>    
  </table>
</div>

<!--モーダルウインドウ表示-->
<div id="edit-overwork-request" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
<div id="edit-superior-announcement" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>